name: CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    # branches:
      # - main
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 22
    name: ${{ matrix.os }} (host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Install dependencies
        run: npm install

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: npm run prebuild -a ${{ env.TARGET }}

      - name: Run tests
        run: npm test

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v5
        with:
          name: prebuilt-binaries-${{ matrix.os }}-${{ matrix.target }}
          path: prebuilds/*
          retention-days: 1

      - name: Upload binaries to GitHub Release
        run: npx prebuild --verbose --upload-all ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/')
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 22
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: prebuilds
      - name: Publish
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$secrets.NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
    

