name: CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    # branches:
      # - main
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 22
        include:
          - os: windows-latest
            node: 22
            host: x86
            target: x86
    name: ${{ matrix.os }} (host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Install dependencies
        run: npm install

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: npm run prebuild -a ${{ env.TARGET }}

      - name: Run tests
        run: npm test

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node == 22
        with:
          name: prebuilt-binaries-${{ matrix.os }}-${{ matrix.target }}
          path: prebuilds/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: npm run upload --upload-all ${{ github.token }}
        if: matrix.node == 22 && startsWith(github.ref, 'refs/tags/')

