name: CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-20.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 22
        include:
          - os: windows-latest
            node: 22
            host: x86
            target: x86
          - os: macos-m1
            node: 22
            host: arm64
            target: arm64
    name: ${{ matrix.os }} (host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Install dependencies
        run: npm install

      - name: Check Node compatibility
        run: node tools/semver-check.js

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: npm prebuild -a ${{ env.TARGET }}

      - name: Run tests
        run: npm test

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node == 22
        with:
          name: prebuilt-binaries
          path: prebuilds/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn upload --upload-all ${{ github.token }}
        if: matrix.node == 18 && startsWith(github.ref, 'refs/tags/')

  build-qemu:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
        target:
          - linux/arm64
        variant:
          - bullseye
          - alpine3.15
        include:
          # musl x64 builds
          - target: linux/amd64
            variant: alpine3.15
            node: 18
    name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries and test
        run: |
          docker buildx build \
            --file ./tools/BinaryBuilder.Dockerfile \
            --load \
            --tag sqlite-builder \
            --platform ${{ matrix.target }} \
            --no-cache \
            --build-arg VARIANT=${{ matrix.variant }} \
            --build-arg NODE_VERSION=${{ matrix.node }} \
            .
          CONTAINER_ID=$(docker create -it sqlite-builder)
          docker cp $CONTAINER_ID:/usr/src/build/prebuilds/ ./prebuilds

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node == 18
        with:
          name: prebuilt-binaries
          path: prebuilds/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn install --ignore-scripts && yarn upload --upload-all ${{ github.token }}
        if: matrix.node == 18 && startsWith(github.ref, 'refs/tags/')
